<?php

class Routes {
	public static final function getListFunction($class, $method, $typeUser) {
		switch ($typeUser) {
			case Constants::$TYPE_USER_ADMIN:
				$res = self::getListFunctionAdmin($class, $method);
				break;
			case Constants::$TYPE_USER_RECEPTION:
				$res = self::getListFunctionRecepcion($class, $method);
				break;
			case Constants::$TYPE_USER_CLIENT:
				$res = self::getListFunctionCliente($class, $method);
				break;
			case Constants::$TYPE_USER_ANDROID:
				$res = self::getListFunctionAndroid($class, $method);
				break;
			case Constants::$TYPE_USER_KITCHEN:
				$res = self::getListFunctionCocina($class, $method);
				break;
			case Constants::$TYPE_USER_SERVICE:
				$res = self::getListFunctionService($class, $method);
				break;
			default:
				$res = self::getListFree($class, $method);
				break;
		}

		return $res;
	}

	/**
	 * @param $class : nombre de la clase
	 * @param $method :' nombre de la funcion
	 * @return string: nombre de la funcion asignada
	 */
	private static final function getListFree($class, $method) {
		$list = array('help'          => array('index'      => 'index',
		                                       'about'      => 'about',
		                                       'manualUser' => 'manualUserFree'),
		              'question'      => array('index'     => 'index',
		                                       'contact'   => 'contact',
		                                       'insert_dd' => 'insert_dd',),
		              'home'          => array('index' => 'index'),
		              'login'         => array('index' => 'index',
		                                       'login' => 'login'),
		              'offer'         => array('index' => 'index',
		                                       'show'  => 'show'),
		              'price'         => array('index' => 'index',
		                                       'print' => 'print'),
		              'reserve'       => array('index'     => 'indexClient',
		                                       'list'      => 'list',
		                                       'panel'     => 'panel',
		                                       'search'    => 'search',
		                                       'checkInfo' => 'checkInfo',
		                                       'pending'   => 'pending',
		                                       'insert'    => 'registerUser'),
		              'service'       => array('index' => 'index',
		                                       'show'  => 'show',),
		              'frequently'    => array('index' => 'index'),
		              'registerAdmin' => array('index' => 'index'),
		              'user'          => array('index'     => 'index',
		                                       'insert_dd' => 'insert_dd'));
		return self::resolveMethod($class, $method, $list);
	}

	/**
	 * @param $class : nombre de la clase
	 * @param $method :' nombre de la funcion
	 * @return string: nombre de la funcion asignada
	 */
	private static final function getListFunctionAdmin($class, $method) {
		$list = array('activity'      => array('index'     => 'index',
		                                       'list'      => 'list',
		                                       'calendar'  => 'calendar',
		                                       'panel'     => 'panel',
		                                       'show'      => 'show',
		                                       'insert'    => 'insert',
		                                       'insert_dd' => 'insert_dd',
		                                       'edit'      => 'edit',
		                                       'edit_dd'   => 'edit_dd',
		                                       'delete_dd' => 'delete_dd'),
		              'chat'          => array('index'     => 'index',
		                                       'profile'   => 'profile',
		                                       'insert'    => 'insert',
		                                       'insert_dd' => 'insert_dd',),
		              'article'       => array('index'     => 'index',
		                                       'insert'    => 'insert',
		                                       'insert_dd' => 'insert_dd',
		                                       'edit'      => 'edit',
		                                       'edit_dd'   => 'edit_dd',
		                                       'delete_dd' => 'delete_dd',),
		              'checkIn'       => array('index'            => 'index',
		                                       'show'             => 'show',
		                                       'insert'           => 'insert',
		                                       'insert_dd'        => 'insert_dd',
		                                       'delete_dd'        => 'delete_dd',
		                                       'search'           => 'search',
		                                       'panel'            => 'panel',
		                                       'deleteConsume_dd' => 'deleteConsume_dd',
		                                       'readPerson'       => 'readPerson',
		                                       'edit'             => 'edit',
		                                       'edit_dd'          => 'edit_dd',
		                                       'list'             => 'list'),
		              'checkOut'      => array('index'     => 'index',
		                                       'edit'      => 'edit',
		                                       'insert_dd' => 'insert_dd',),
		              'checkTeam'     => array('index'   => 'index',
		                                       'edit'    => 'edit',
		                                       'edit_dd' => 'edit_dd'),
		              'consume'       => array('index'           => 'index',
		                                       'show'            => 'show',
		                                       'service'         => 'service',
		                                       'food'            => 'food',
		                                       'saveConsume'     => 'saveConsume',
		                                       'saveConsumeFood' => 'saveConsumeFood',
		                                       'offer'           => 'offer',
		                                       'search'          => 'search'),
		              'print'         => array('index'   => 'index',
		                                       'check'   => 'check',
		                                       'billing' => 'billing',
		                                       'reserve' => 'reserve'),
		              'food'          => array('index'     => 'index',
		                                       'panel'     => 'panel',
		                                       'insert'    => 'insert',
		                                       'show'      => 'show',
		                                       'edit'      => 'edit',
		                                       'edit_dd'   => 'edit_dd',
		                                       'delete_dd' => 'delete_dd',
		                                       'insert_dd' => 'insert_dd'),
		              'help'          => array('index'               => 'index',
		                                       'question'            => 'question',
		                                       'contact'             => 'contact',
		                                       'complaint'           => 'complaint',
		                                       'about'               => 'about',
		                                       'manualUserAndroid'   => 'manualUserAndroid',
		                                       'manualUserService'   => 'manualUserService',
		                                       'manualUserClient'    => 'manualUserClient',
		                                       'manualUserCocina'    => 'manualUserCocina',
		                                       'manualUserAdmin'     => 'manualUserAdmin',
		                                       'manualUserReception' => 'manualUserReception'),
		              'history'       => array('index' => 'index',
		                                       'show'  => 'show'),
		              'home'          => array('index' => 'indexAdmin'),
		              'login'         => array('logout' => 'logout'),
		              'hotel'         => array('index'     => 'index',
		                                       'edit'      => 'edit',
		                                       'insert_dd' => 'insert_dd'),
		              'report'        => array('index'   => 'index',
		                                       'inquest' => 'inquest'),
		              'inquest'       => array('index'        => 'index',
		                                       'panel'        => 'panel',
		                                       'delete_dd'    => 'delete_dd',
		                                       'edit'         => 'edit',
		                                       'edit_dd'      => 'edit_dd',
		                                       'questionList' => 'questionList',
		                                       'responseList' => 'responseList',
		                                       'fillInquest'  => 'fillInquest',
		                                       'saveFill'     => 'saveFill',
		                                       'insert'       => 'insert',
		                                       'insert_dd'    => 'insert_dd'),
		              'menu'          => array('index'     => 'index',
		                                       'show'      => 'show',
		                                       'panel'     => 'panel',
		                                       'insert'    => 'insert',
		                                       'edit'      => 'edit',
		                                       'edit_dd'   => 'edit_dd',
		                                       'delete_dd' => 'delete_dd',
		                                       'insert_dd' => 'insert_dd'),
		              'messages'      => array('index'     => 'index',
		                                       'show'      => 'show',
		                                       'insert'    => 'insert',
		                                       'insert_dd' => 'insert_dd'),
		              'offer'         => array('index'     => 'index',
		                                       'panel'     => 'panel',
		                                       'show'      => 'show',
		                                       'delete_dd' => 'delete_dd',
		                                       'insert'    => 'insert',
		                                       'insert_dd' => 'insert_dd',
		                                       'edit'      => 'edit',
		                                       'edit_dd'   => 'edit_dd'),
		              'order'         => array('index'     => 'index',
		                                       'insert_dd' => 'insert_dd'),
		              'price'         => array('index' => 'index',
		                                       'print' => 'print'),
		              'profile'       => array('index'      => 'index',
		                                       'show'       => 'show',
		                                       'edit_dd'    => 'edit_dd',
		                                       'edit'       => 'edit',
		                                       'list'       => 'list',
		                                       'listClient' => 'listClient'),
		              'user'          => array('index'  => 'index',
		                                       'insert' => 'insert'),
		              'registerAdmin' => array('index' => 'index'),
		              'reserve'       => array('index'                    => 'index',
		                                       'indexClient'              => 'indexClient',
		                                       'list'                     => 'list',
		                                       'search'                   => 'search',
		                                       'checkInfo'                => 'checkInfo',
		                                       'pending'                  => 'pending',
		                                       'deletePending'            => 'deletePending',
		                                       'savePending'              => 'savePending',
		                                       'insert'                   => 'insert',
		                                       'saveReserve'              => 'saveReserve',
		                                       'deleteConsume_dd'         => 'deleteConsume_dd',
		                                       'deleteCheck'              => 'deleteCheck',
		                                       'editConsume'              => 'editConsume',
		                                       'editIncumbent'            => 'editIncumbent',
		                                       'editReserve'              => 'editReserve',
		                                       'editReserveTeam'          => 'editReserveTeam',
		                                       'show'                     => 'show',
		                                       'updateTeam'               => 'updateTeam',
		                                       'updateIncumbent'          => 'updateIncumbent',
		                                       'updateReserveCheckIn'     => 'updateReserveCheckIn',
		                                       'updateReserveCheckInTeam' => 'updateReserveCheckInTeam',
		                                       'updateValidCard'          => 'updateValidCard'),
		              'room'          => array('index'     => 'index',
		                                       'panel'     => 'panel',
		                                       'insert'    => 'insert',
		                                       'edit'      => 'edit',
		                                       'delete_dd' => 'delete_dd',
		                                       'insert_dd' => 'insert_dd',
		                                       'edit_dd'   => 'edit_dd',
		                                       'calendar'  => 'calendar'),
		              'state'         => array('index'     => 'index',
		                                       'delete_dd' => 'delete_dd',
		                                       'edit_dd'   => 'edit_dd',
		                                       'insert'    => 'insert',
		                                       'list'      => 'list'),
		              'type'          => array('index'       => 'index',
		                                       'edit'        => 'edit',
		                                       'delete_dd'   => 'delete_dd',
		                                       'insert'      => 'insert',
		                                       'edit_dd'     => 'edit_dd',
		                                       'list'        => 'list',
		                                       'editOffer'   => 'editOffer',
		                                       'deleteOffer' => 'deleteOffer',
		                                       'insertOffer' => 'insertOffer',
		                                       'updateOffer' => 'updateOffer',
		                                       'listOffer'   => 'listOffer',),
		              'typeRoom'      => array('index'     => 'index',
		                                       'edit'      => 'edit',
		                                       'delete_dd' => 'delete_dd',
		                                       'insert'    => 'insert',
		                                       'edit_dd'   => 'edit_dd'),
		              'rule'          => array('index'     => 'index',
		                                       'insert_dd' => 'insert_dd',
		                                       'delete_dd' => 'delete_dd',
		                                       'edit_dd'   => 'edit_dd',),
		              'search'        => array('index' => 'index'),
		              'service'       => array('index'     => 'index',
		                                       'panel'     => 'panel',
		                                       'show'      => 'show',
		                                       'delete_dd' => 'delete_dd',
		                                       'edit'      => 'edit',
		                                       'edit_dd'   => 'edit_dd',
		                                       'insert'    => 'insert',
		                                       'insert_dd' => 'insert_dd',),
		              'site'          => array('index'     => 'index',
		                                       'insert'    => 'insert',
		                                       'insert_dd' => 'insert_dd',
		                                       'show'      => 'show',
		                                       'panel'     => 'panel',
		                                       'delete_dd' => 'delete_dd',
		                                       'edit'      => 'edit',
		                                       'edit_dd'   => 'edit_dd'),
		              'suggestion'    => array('index' => 'index'),
		              'settings'      => array('index' => 'index'),
		              'frequently'    => array('index'     => 'index',
		                                       'panel'     => 'panel',
		                                       'insert'    => 'insert',
		                                       'edit'      => 'edit',
		                                       'delete_dd' => 'delete_dd'));
		return self::resolveMethod($class, $method, $list);
	}

	/**
	 * verificar si el usuario tiene lo permisos para acceder a las paginas solicitadas
	 *
	 * @param $class : nombre del controlador
	 * @param $method : nombre de la funcion
	 * @return string: nombre del controlador permitido
	 */
	private static final function getListFunctionAndroid($class, $method) {
		$list = array('chat'           => array('index'   => 'index',
		                                        'profile' => 'profile',
		                                        'insert'  => 'insert',
		                                        'talk'    => 'talk',),
		              'login'          => array('index' => 'index'),
		              'complaints'     => array('index' => 'index'),
		              'contact'        => array('index' => 'index'),
		              'frequently'     => array('index' => 'index'),
		              'history'        => array('index' => 'index'),
		              'home'           => array('index' => 'index'),
		              'info'           => array('index' => 'index'),
		              'offer'          => array('index' => 'index'),
		              'profile'        => array('index'  => 'index',
		                                        'upload' => 'upload'),
		              'reserve'        => array('index'  => 'index',
		                                        'save'   => 'save',
		                                        'cancel' => 'cancel'),
		              'service'        => array('index'  => 'index',
		                                        'insert' => 'insert'),
		              'sites'          => array('index' => 'index'),
		              'suggestion'     => array('index' => 'index'),
		              'foodMenu'       => array('index'  => 'index',
		                                        'update' => 'update'),
		              'messages'       => array('index' => 'index'),
		              'calendar'       => array('index' => 'index'),
		              'createAccount'  => array('index' => 'index'),
		              'check'          => array('index' => 'index'),
		              'member'         => array('index' => 'index',
		                                        'save'  => 'save'),
		              'consumeService' => array('index' => 'index'));
		return self::resolveMethod($class, $method, $list);
	}

	/**
	 * @param $class : nombre de la clase
	 * @param $method :' nombre de la funcion
	 * @return string: nombre de la funcion asignada
	 */
	private static final function getListFunctionCliente($class, $method) {
		$list = array('activity'    => array('index'    => 'index',
		                                     'calendar' => 'calendar',
		                                     'show'     => 'show'),
		              'chat'        => array('index'     => 'index',
		                                     'profile'   => 'profile',
		                                     'insert'    => 'insert',
		                                     'insert_dd' => 'insert_dd'),
		              'checkIn'     => array('readPerson' => 'readPerson',
		                                     'show'       => 'show'),
		              'help'        => array('index'      => 'index',
		                                     'about'      => 'about',
		                                     'manualUser' => 'manualUserClient'),
		              'question'    => array('index'          => 'index',
		                                     'contact'        => 'index',
		                                     'insertQuestion' => 'insertQuestion',
		                                     'suggestion'     => 'suggestion',
		                                     'complaint'      => 'complaint',
		                                     'insert_dd'      => 'insert_dd',),
		              'history'     => array('index' => 'index',
		                                     'show'  => 'show'),
		              'consume'     => array('index' => 'consumeCheck',
		                                     'show'  => 'show'),
		              'frequently'  => array('index' => 'index',
		                                     'list'  => 'list'),
		              'home'        => array('index' => 'indexClient'),
		              'login'       => array('logout' => 'logout'),
		              'inquest'     => array('index'        => 'index',
		                                     'questionList' => 'fillInquest',
		                                     'edit_dd'      => 'edit_dd',
		                                     'fillInquest'  => 'fillInquest',
		                                     'saveFill'     => 'saveFill'),
		              'messages'    => array('index'     => 'index',
		                                     'show'      => 'show',
		                                     'insert'    => 'insert',
		                                     'insert_dd' => 'insert_dd'),
		              'food'        => array('index' => 'index',
		                                     'show'  => 'show'),
		              'offer'       => array('index' => 'index',
		                                     'show'  => 'show'),
		              'typeOffer'   => array('index'     => 'index',
		                                     'edit'      => 'edit',
		                                     'delete_dd' => 'delete_dd',
		                                     'insert'    => 'insert',
		                                     'edit_dd'   => 'edit_dd'),
		              'price'       => array('index' => 'index',
		                                     'print' => 'print'),
		              'profile'     => array('index'   => 'index',
		                                     'show'    => 'show',
		                                     'edit_dd' => 'edit_dd',
		                                     'edit'    => 'edit'),
		              'reserve'     => array('index'                    => 'indexClient',
		                                     'list'                     => 'listClient',
		                                     'search'                   => 'search',
		                                     'checkInfo'                => 'checkInfo',
		                                     'pending'                  => 'pending',
		                                     'insert'                   => 'insertClient',
		                                     'saveReserve'              => 'saveReserveClient',
		                                     'deleteConsume_dd'         => 'deleteConsume_dd',
		                                     'deleteCheck'              => 'deleteCheck',
		                                     'editConsume'              => 'editConsume',
		                                     'editIncumbent'            => 'editIncumbent',
		                                     'editReserve'              => 'editReserve',
		                                     'editReserveTeam'          => 'editReserveTeam',
		                                     'updateTeam'               => 'updateTeam',
		                                     'updateIncumbent'          => 'updateIncumbent',
		                                     'updateReserveCheckIn'     => 'updateReserveCheckIn',
		                                     'updateReserveCheckInTeam' => 'updateReserveCheckInTeam',),
		              'typeReserve' => array('index'     => 'index',
		                                     'edit'      => 'edit',
		                                     'delete_dd' => 'delete_dd',
		                                     'insert'    => 'insert',
		                                     'edit_dd'   => 'edit_dd'),
		              'search'      => array('index' => 'index'),
		              'service'     => array('index' => 'index',
		                                     'show'  => 'show'),
		              'site'        => array('index' => 'index',
		                                     'show'  => 'show'),
		              'suggestion'  => array('index' => 'index'),
		              'user'       => array('index'     => 'index',
		                                    'insert_dd' => 'insert_dd',
		                                    'insert'    => 'insertClient'));

		return self::resolveMethod($class, $method, $list);
	}

	/**
	 * @param $class : nombre de la clase
	 * @param $method :' nombre de la funcion
	 * @return string: nombre de la funcion asignada
	 */
	private static final function getListFunctionCocina($class, $method) {
		$list = array('site'       => array('index' => 'index',
		                                    'list'  => 'list',
		                                    'show'  => 'show',),
		              'activity'   => array('index'    => 'index',
		                                    'list'     => 'list',
		                                    'calendar' => 'calendar',
		                                    'show'     => 'show'),
		              'chat'       => array('index'     => 'index',
		                                    'profile'   => 'profile',
		                                    'insert'    => 'insert',
		                                    'insert_dd' => 'insert_dd',),
		              'checkIn'    => array('index'            => 'index',
		                                    'show'             => 'show',
		                                    'insert'           => 'insert',
		                                    'insert_dd'        => 'insert_dd',
		                                    'delete_dd'        => 'delete_dd',
		                                    'search'           => 'search',
		                                    'deleteConsume_dd' => 'deleteConsume_dd',
		                                    'readPerson'       => 'readPerson',
		                                    'edit'             => 'edit',
		                                    'edit_dd'          => 'edit_dd'),
		              'checkOut'   => array('index'     => 'index',
		                                    'edit'      => 'edit',
		                                    'insert_dd' => 'insert_dd',),
		              'checkTeam'  => array('index'   => 'index',
		                                    'edit'    => 'edit',
		                                    'edit_dd' => 'edit_dd'),
		              'consume'    => array('index'           => 'index',
		                                    'show'            => 'show',
		                                    'service'         => 'service',
		                                    'food'            => 'food',
		                                    'saveConsume'     => 'saveConsume',
		                                    'saveConsumeFood' => 'saveConsumeFood',
		                                    'offer'           => 'offer'),
		              'food'       => array('index'     => 'index',
		                                    'list'      => 'list',
		                                    'panel'     => 'panel',
		                                    'insert'    => 'insert',
		                                    'show'      => 'show',
		                                    'edit'      => 'edit',
		                                    'edit_dd'   => 'edit_dd',
		                                    'delete_dd' => 'delete_dd',
		                                    'insert_dd' => 'insert_dd'),
		              'typeFood'   => array('index'     => 'index',
		                                    'edit'      => 'edit',
		                                    'delete_dd' => 'delete_dd',
		                                    'insert'    => 'insert',
		                                    'edit_dd'   => 'edit_dd'),
		              'stateFood'  => array('index'     => 'index',
		                                    'delete_dd' => 'delete_dd',
		                                    'edit_dd'   => 'edit_dd',
		                                    'insert'    => 'insert'),
		              'help'       => array('index'      => 'index',
		                                    'contact'    => 'contact',
		                                    'about'      => 'about',
		                                    'manualUser' => 'manualUserCocina'),
		              'history'    => array('index' => 'index',
		                                    'show'  => 'show'),
		              'home'       => array('index' => 'indexCocina'),
		              'login'      => array('logout' => 'logout'),
		              'inquest'    => array('index'       => 'fillInquest',
		                                    'fillInquest' => 'fillInquest',
		                                    'saveFill'    => 'saveFill',),
		              'menu'       => array('list'      => 'list',
		                                    'show'      => 'show',
		                                    'panel'     => 'panel',
		                                    'insert'    => 'insert',
		                                    'edit'      => 'edit',
		                                    'edit_dd'   => 'edit_dd',
		                                    'delete_dd' => 'delete_dd',
		                                    'insert_dd' => 'insert_dd'),
		              'messages'   => array('index'     => 'index',
		                                    'show'      => 'show',
		                                    'insert'    => 'insert',
		                                    'insert_dd' => 'insert_dd'),
		              'order'      => array('index'     => 'index',
		                                    'insert_dd' => 'insert_dd'),
		              'profile'    => array('index'   => 'index',
		                                    'show'    => 'show',
		                                    'edit_dd' => 'edit_dd',
		                                    'edit'    => 'edit',
		                                    'list'    => 'list'),
		              'user'       => array('index'     => 'index',
		                                    'insert_dd' => 'insert_dd'),
		              'frequently' => array('index' => 'index',
		                                    'list'  => 'list',),
		              'type'       => array('index'  => 'index',
		                                    'edit'   => 'edit',
		                                    'insert' => 'insert',
		                                    'list'   => 'list',),
		              'service'    => array('index' => 'index',
		                                    'list'  => 'list',
		                                    'show'  => 'show',),);
		return self::resolveMethod($class, $method, $list);
	}

	/**
	 * @param $class : nombre de la clase
	 * @param $method :' nombre de la funcion
	 * @return string: nombre de la funcion asignada
	 */
	private static final function getListFunctionRecepcion($class, $method) {
		$list = array('activity'   => array('index'    => 'index',
		                                    'panel'    => 'panel',
		                                    'list'     => 'list',
		                                    'calendar' => 'calendar',
		                                    'show'     => 'show',),
		              'chat'       => array('index'     => 'index',
		                                    'profile'   => 'profile',
		                                    'insert'    => 'insert',
		                                    'insert_dd' => 'insert_dd',),
		              'checkIn'    => array('index'            => 'index',
		                                    'show'             => 'show',
		                                    'insert'           => 'insert',
		                                    'insert_dd'        => 'insert_dd',
		                                    'delete_dd'        => 'delete_dd',
		                                    'search'           => 'search',
		                                    'deleteConsume_dd' => 'deleteConsume_dd',
		                                    'readPerson'       => 'readPerson',
		                                    'edit'             => 'edit',
		                                    'panel'            => 'panel',
		                                    'edit_dd'          => 'edit_dd'),
		              'checkOut'   => array('index'     => 'index',
		                                    'edit'      => 'edit',
		                                    'insert_dd' => 'insert_dd',),
		              'checkTeam'  => array('index'   => 'index',
		                                    'edit'    => 'edit',
		                                    'edit_dd' => 'edit_dd'),
		              'consume'    => array('index'           => 'index',
		                                    'show'            => 'show',
		                                    'service'         => 'service',
		                                    'food'            => 'food',
		                                    'saveConsume'     => 'saveConsume',
		                                    'saveConsumeFood' => 'saveConsumeFood',
		                                    'offer'           => 'offer'),
		              'print'      => array('index'   => 'index',
		                                    'check'   => 'check',
		                                    'billing' => 'billing',
		                                    'reserve' => 'reserve'),
		              'food'       => array('index' => 'index',
		                                    'show'  => 'show'),
		              'help'       => array('index'      => 'index',
		                                    'question'   => 'question',
		                                    'contact'    => 'contact',
		                                    'complaint'  => 'complaint',
		                                    'about'      => 'about',
		                                    'manualUser' => 'manualUserReception'),
		              'history'    => array('index' => 'index',
		                                    'show'  => 'show'),
		              'home'       => array('index' => 'indexReception'),
		              'login'      => array('logout' => 'logout'),
		              'inquest'    => array('index'       => 'fillInquest',
		                                    'fillInquest' => 'fillInquest',
		                                    'saveFill'    => 'saveFill',),
		              'menu'       => array('list'   => 'list',
		                                    'show'   => 'show',
		                                    'insert' => 'insert'),
		              'messages'   => array('index'     => 'index',
		                                    'show'      => 'show',
		                                    'insert'    => 'insert',
		                                    'insert_dd' => 'insert_dd'),
		              'offer'      => array('index'     => 'index',
		                                    'list'      => 'list',
		                                    'panel'     => 'panel',
		                                    'show'      => 'show',
		                                    'delete_dd' => 'delete_dd',
		                                    'insert'    => 'insert',
		                                    'insert_dd' => 'insert_dd',
		                                    'edit'      => 'edit',
		                                    'edit_dd'   => 'edit_dd',),
		              'order'      => array('index'     => 'index',
		                                    'insert_dd' => 'insert_dd'),
		              'price'      => array('index' => 'index',
		                                    'print' => 'print'),
		              'profile'    => array('index'   => 'index',
		                                    'show'    => 'show',
		                                    'edit_dd' => 'edit_dd',
		                                    'edit'    => 'edit',
		                                    'list'    => 'listClient',),
		              'user'       => array('index'     => 'index',
		                                    'insert_dd' => 'insert_dd',
		                                    'insert'    => 'insertClient'),
		              'reserve'    => array('index'                    => 'index',
		                                    'list'                     => 'list',
		                                    'panel'                    => 'panel',
		                                    'search'                   => 'search',
		                                    'checkInfo'                => 'checkInfo',
		                                    'pending'                  => 'pending',
		                                    'deletePending'            => 'deletePending',
		                                    'savePending'              => 'savePending',
		                                    'insert'                   => 'insert',
		                                    'saveReserve'              => 'saveReserve',
		                                    'deleteConsume_dd'         => 'deleteConsume_dd',
		                                    'deleteCheck'              => 'deleteCheck',
		                                    'editConsume'              => 'editConsume',
		                                    'editIncumbent'            => 'editIncumbent',
		                                    'editReserve'              => 'editReserve',
		                                    'editReserveTeam'          => 'editReserveTeam',
		                                    'updateTeam'               => 'updateTeam',
		                                    'updateIncumbent'          => 'updateIncumbent',
		                                    'updateReserveCheckIn'     => 'updateReserveCheckIn',
		                                    'updateReserveCheckInTeam' => 'updateReserveCheckInTeam',
		                                    'updateValidCard'          => 'updateValidCard'),
		              'room'       => array('index'     => 'index',
		                                    'list'      => 'list',
		                                    'panel'     => 'panel',
		                                    'insert'    => 'insert',
		                                    'edit'      => 'edit',
		                                    'delete_dd' => 'delete_dd',
		                                    'insert_dd' => 'insert_dd',
		                                    'edit_dd'   => 'edit_dd',
		                                    'calendar'  => 'calendar'),
		              'rule'       => array('index' => 'index',
		                                    'list'  => 'list'),
		              'search'     => array('index' => 'index'),
		              'service'    => array('index'     => 'index',
		                                    'list'      => 'list',
		                                    'panel'     => 'panel',
		                                    'show'      => 'show',
		                                    'delete_dd' => 'delete_dd',
		                                    'edit'      => 'edit',
		                                    'edit_dd'   => 'edit_dd',
		                                    'insert'    => 'insert',
		                                    'insert_dd' => 'insert_dd'),
		              'site'       => array('index'     => 'index',
		                                    'list'      => 'list',
		                                    'insert'    => 'insert',
		                                    'insert_dd' => 'insert_dd',
		                                    'show'      => 'show',
		                                    'panel'     => 'panel',
		                                    'delete_dd' => 'delete_dd',
		                                    'edit'      => 'edit',
		                                    'edit_dd'   => 'edit_dd'),
		              'suggestion' => array('index' => 'index'),
		              'frequently' => array('index'     => 'index',
		                                    'list'      => 'list',
		                                    'panel'     => 'panel',
		                                    'insert'    => 'insert',
		                                    'edit'      => 'edit',
		                                    'delete_dd' => 'delete_dd',));
		return self::resolveMethod($class, $method, $list);
	}

	/**
	 * @param $class : nombre de la clase
	 * @param $method :' nombre de la funcion
	 * @return string: nombre de la funcion asignada
	 */
	private static final function getListFunctionService($class, $method) {
		$list = array('activity'   => array('index'    => 'index',
		                                    'list'     => 'list',
		                                    'calendar' => 'calendar',
		                                    'show'     => 'show',),
		              'chat'       => array('index'     => 'index',
		                                    'profile'   => 'profile',
		                                    'insert'    => 'insert',
		                                    'insert_dd' => 'insert_dd',),
		              'check'      => array('index'            => 'index',
		                                    'tableCheckIn'     => 'tableCheckIn',
		                                    'showConsum'       => 'showConsum',
		                                    'search'           => 'search',
		                                    'outPanel'         => 'outPanel',
		                                    'editConsume'      => 'editConsume',
		                                    'editIncumbent'    => 'editIncumbent',
		                                    'editCheckOut'     => 'editCheckOut',
		                                    'deleteConsume_dd' => 'deleteConsume_dd',
		                                    'deleteCheck'      => 'deleteCheck',
		                                    'updateTeam'       => 'updateTeam',
		                                    'updateIncumbent'  => 'updateIncumbent',
		                                    'saveCheckIn'      => 'saveCheckIn',
		                                    'saveCheckOut'     => 'saveCheckOut',
		                                    'insert'           => 'insert',),
		              'consume'    => array('index'           => 'index',
		                                    'show'            => 'show',
		                                    'service'         => 'service',
		                                    'food'            => 'food',
		                                    'saveConsume'     => 'saveConsume',
		                                    'saveConsumeFood' => 'saveConsumeFood',
		                                    'offer'           => 'offer'),
		              'help'       => array('index'      => 'index',
		                                    'contact'    => 'contact',
		                                    'about'      => 'about',
		                                    'insert_dd'  => 'insert_dd',
		                                    'manualUser' => 'manualUserReception'),
		              'history'    => array('index' => 'index',
		                                    'show'  => 'show'),
		              'home'       => array('index' => 'indexService'),
		              'login'      => array('logout' => 'logout'),
		              'inquest'    => array('index'       => 'fillInquest',
		                                    'fillInquest' => 'fillInquest',
		                                    'saveFill'    => 'saveFill',),
		              'menu'       => array('list'   => 'list',
		                                    'show'   => 'show',
		                                    'insert' => 'insert'),
		              'messages'   => array('index'     => 'index',
		                                    'show'      => 'show',
		                                    'insert'    => 'insert',
		                                    'insert_dd' => 'insert_dd'),
		              'order'      => array('index'     => 'index',
		                                    'insert_dd' => 'insert_dd'),
		              'profile'    => array('index'   => 'index',
		                                    'show'    => 'show',
		                                    'edit_dd' => 'edit_dd',
		                                    'edit'    => 'edit',
		                                    'list'    => 'list'),
		              'user'       => array('index'     => 'index',
		                                    'insert_dd' => 'insert_dd'),
		              'frequently' => array('index' => 'index',
		                                    'list'  => 'list',),
		              'food'       => array('index' => 'index',
		                                    'show'  => 'show'),
		              'site'       => array('index' => 'index',
		                                    'list'  => 'list',
		                                    'show'  => 'show',),
		              'service'    => array('index' => 'index',
		                                    'list'  => 'list',
		                                    'show'  => 'show',),);
		return self::resolveMethod($class, $method, $list);
	}

	/**
	 * @param $class
	 * @param $method
	 * @param $list
	 * @return mixed
	 */
	private static function resolveMethod($class, $method, $list) {

		$res = '';
		if (isset($list[$class][$method]))
			$res = $list[$class][$method];

		return $res;
	}
}
