/*
 Navicat Premium Data Transfer

 Source Server         : 127.0.0.1
 Source Server Type    : MySQL
 Source Server Version : 100124
 Source Host           : localhost:3306
 Source Schema         : hotel

 Target Server Type    : MySQL
 Target Server Version : 100124
 File Encoding         : 65001

 Date: 10/10/2018 20:14:35
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for activity
-- ----------------------------
DROP TABLE IF EXISTS `activity`;
CREATE TABLE `activity`  (
  `ID_ACTIVITY` int(11) NOT NULL AUTO_INCREMENT,
  `ID_TYPE_ACTIVITY` int(11) NOT NULL,
  `ID_STATE_ACTIVITY` int(11) NOT NULL,
  `NAME_ACTIVITY` char(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_ACTIVITY` varchar(350) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_START_ACTIVITY` date NOT NULL,
  `TIME_START_ACTIVITY` time(0) NOT NULL,
  `DATE_END_ACTIVITY` date NOT NULL,
  `TIME_END_ACTIVITY` time(0) NOT NULL,
  `IMAGE_ACTIVITY` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`ID_ACTIVITY`) USING BTREE,
  INDEX `FK_RELATIONSHIP_92`(`ID_TYPE_ACTIVITY`) USING BTREE,
  INDEX `FK_RELATIONSHIP_93`(`ID_STATE_ACTIVITY`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_92` FOREIGN KEY (`ID_TYPE_ACTIVITY`) REFERENCES `type_activity` (`ID_TYPE_ACTIVITY`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_93` FOREIGN KEY (`ID_STATE_ACTIVITY`) REFERENCES `state_activity` (`ID_STATE_ACTIVITY`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 21 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for article
-- ----------------------------
DROP TABLE IF EXISTS `article`;
CREATE TABLE `article`  (
  `ID_ARTICLE` int(11) NOT NULL AUTO_INCREMENT,
  `NAME_ARTICLE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_ARTICLE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `STATE_ARTICLE` decimal(1, 0) NOT NULL,
  `UNIT_ARTICLE` int(11) NOT NULL,
  PRIMARY KEY (`ID_ARTICLE`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 17 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for article_consum
-- ----------------------------
DROP TABLE IF EXISTS `article_consum`;
CREATE TABLE `article_consum`  (
  `ID_ARTICLE` int(11) NOT NULL,
  `ID_CONSUME_SERVICE` int(11) NOT NULL,
  `ID_STATE_ARTICLE` int(11) NOT NULL,
  PRIMARY KEY (`ID_ARTICLE`, `ID_CONSUME_SERVICE`) USING BTREE,
  INDEX `FK_RELATIONSHIP_105`(`ID_CONSUME_SERVICE`) USING BTREE,
  INDEX `FK_RELATIONSHIP_109`(`ID_STATE_ARTICLE`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_102` FOREIGN KEY (`ID_ARTICLE`) REFERENCES `article` (`ID_ARTICLE`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_105` FOREIGN KEY (`ID_CONSUME_SERVICE`) REFERENCES `consume_service` (`ID_CONSUME_SERVICE`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_109` FOREIGN KEY (`ID_STATE_ARTICLE`) REFERENCES `state_article` (`ID_STATE_ARTICLE`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for bill
-- ----------------------------
DROP TABLE IF EXISTS `bill`;
CREATE TABLE `bill`  (
  `ID_BILL` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_BILL` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `ID_PERSON` int(11) NOT NULL,
  `ID_PERSON_SENDER` int(11) NOT NULL,
  `ID_CHECK` int(11) NOT NULL,
  `CONSUME_BILL` float(8, 2) NOT NULL,
  `DATE_BILL` date NOT NULL,
  `TIME_BILL` time(0) NOT NULL,
  PRIMARY KEY (`ID_BILL`) USING BTREE,
  INDEX `FK_RELATIONSHIP_59`(`ID_PERSON`) USING BTREE,
  INDEX `FK_RELATIONSHIP_89`(`ID_CHECK`) USING BTREE,
  INDEX `FK_RELATIONSHIP_90`(`ID_PERSON_SENDER`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_59` FOREIGN KEY (`ID_PERSON`) REFERENCES `person` (`ID_PERSON`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_89` FOREIGN KEY (`ID_CHECK`) REFERENCES `check_person` (`ID_CHECK`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_90` FOREIGN KEY (`ID_PERSON_SENDER`) REFERENCES `person` (`ID_PERSON`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for card
-- ----------------------------
DROP TABLE IF EXISTS `card`;
CREATE TABLE `card`  (
  `ID_CARD` int(8) NOT NULL AUTO_INCREMENT,
  `ID_CHECK` int(11) NOT NULL,
  `NUMBER_CARD` varchar(150) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `ID_TYPE_CARD` int(11) NOT NULL,
  `MONTH_CARD` decimal(2, 0) NOT NULL,
  `YEAR_CARD` decimal(4, 0) NOT NULL,
  `CCV_CARD` decimal(3, 0) NOT NULL,
  `VALID_CARD` tinyint(1) NOT NULL,
  `TYPE_MONEY_CARD` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DEPOSIT_CARD` float(8, 2) NOT NULL,
  PRIMARY KEY (`ID_CARD`) USING BTREE,
  INDEX `FK_RELATIONSHIP_86`(`ID_CHECK`) USING BTREE,
  INDEX `FK_RELATIONSHIP_87`(`ID_TYPE_CARD`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_86` FOREIGN KEY (`ID_CHECK`) REFERENCES `check_person` (`ID_CHECK`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_87` FOREIGN KEY (`ID_TYPE_CARD`) REFERENCES `type_card` (`ID_TYPE_CARD`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 5 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for check_person
-- ----------------------------
DROP TABLE IF EXISTS `check_person`;
CREATE TABLE `check_person`  (
  `ID_CHECK` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PERSON_TITULAR` int(11) DEFAULT NULL,
  `ID_PERSON_RECEPTION` int(11) NOT NULL,
  `ID_HOTEL` int(11) NOT NULL,
  `ID_STATE_CHECK` int(11) NOT NULL,
  `DATE_START_CHECK` date NOT NULL,
  `TIME_START_CHECK` time(0) NOT NULL,
  `DATE_END_CHECK` date NOT NULL,
  `TIME_END_CHECK` time(0) NOT NULL,
  `OBSERVATIONS_CHECK` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `ID_TYPE_CHECK` int(11) NOT NULL,
  `DATE_CREATED_CHECK` date NOT NULL,
  `TIME_CREATED_CHECK` time(0) NOT NULL,
  `DATE_UPDATE_CHECK` date NOT NULL,
  `TIME_UPDATE_CHECK` time(0) NOT NULL,
  PRIMARY KEY (`ID_CHECK`) USING BTREE,
  INDEX `FK_RELATIONSHIP_100`(`ID_PERSON_TITULAR`) USING BTREE,
  INDEX `FK_RELATIONSHIP_110`(`ID_HOTEL`) USING BTREE,
  INDEX `FK_RELATIONSHIP_123`(`ID_PERSON_RECEPTION`) USING BTREE,
  INDEX `FK_RELATIONSHIP_85`(`ID_STATE_CHECK`) USING BTREE,
  INDEX `FK_RELATIONSHIP_88`(`ID_TYPE_CHECK`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_100` FOREIGN KEY (`ID_PERSON_TITULAR`) REFERENCES `person` (`ID_PERSON`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_110` FOREIGN KEY (`ID_HOTEL`) REFERENCES `hotel` (`ID_HOTEL`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_123` FOREIGN KEY (`ID_PERSON_RECEPTION`) REFERENCES `person` (`ID_PERSON`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_85` FOREIGN KEY (`ID_STATE_CHECK`) REFERENCES `state_check` (`ID_STATE_CHECK`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_88` FOREIGN KEY (`ID_TYPE_CHECK`) REFERENCES `type_check` (`ID_TYPE_CHECK`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 70 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for consume_food
-- ----------------------------
DROP TABLE IF EXISTS `consume_food`;
CREATE TABLE `consume_food`  (
  `ID_CONSUME_FOOD` int(11) NOT NULL AUTO_INCREMENT,
  `ID_CHECK` int(11) NOT NULL,
  `ID_FOOD` int(11) NOT NULL,
  `ID_TYPE_MONEY` int(11) NOT NULL,
  `UNIT_COST_FOOD` decimal(3, 0) NOT NULL,
  `PRICE_CONSUME_FOOD` float(8, 2) NOT NULL,
  `PAY_CONSUME_FOOD` float(8, 2) NOT NULL,
  `TIME_CONSUME_FOOD` time(0) NOT NULL,
  `DATE_CONSUME_FOOD` date NOT NULL,
  `UNIT_CONSUME_FOOD` decimal(5, 0) NOT NULL,
  `STATE_CONSUME_FOOD` decimal(1, 0) NOT NULL,
  `SITE_CONSUME_FOOD` varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`ID_CONSUME_FOOD`, `ID_CHECK`) USING BTREE,
  INDEX `FK_RELATIONSHIP_106`(`ID_CHECK`) USING BTREE,
  INDEX `FK_RELATIONSHIP_98`(`ID_FOOD`, `ID_TYPE_MONEY`, `UNIT_COST_FOOD`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_106` FOREIGN KEY (`ID_CHECK`) REFERENCES `check_person` (`ID_CHECK`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_98` FOREIGN KEY (`ID_FOOD`, `ID_TYPE_MONEY`, `UNIT_COST_FOOD`) REFERENCES `cost_food` (`ID_FOOD`, `ID_TYPE_MONEY`, `UNIT_COST_FOOD`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 4 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for consume_service
-- ----------------------------
DROP TABLE IF EXISTS `consume_service`;
CREATE TABLE `consume_service`  (
  `ID_CONSUME_SERVICE` int(11) NOT NULL AUTO_INCREMENT,
  `ID_CHECK` int(11) NOT NULL,
  `ID_TYPE_CONSUME` int(11) NOT NULL,
  `ID_COST_SERVICE` int(11) NOT NULL,
  `DATE_START_CONSUME_SERVICE` date NOT NULL,
  `TIME_START_CONSUME_SERVICE` time(0) NOT NULL,
  `DATE_END_CONSUME_SERVICE` date NOT NULL,
  `TIME_END_CONSUME_SERVICE` time(0) NOT NULL,
  `PAY_CONSUME_SERVICE` float(8, 2) NOT NULL,
  `PRICE_CONSUME_SERVICE` float(8, 2) NOT NULL,
  `DETAIL_CONSUME_SERVICE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `ACTIVE_CONSUME_SERVICE` tinyint(1) NOT NULL,
  `UNIT_CONSUME_SERVICE` int(11) NOT NULL,
  `IMAGE_DEPOSIT` varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `TYPE_PAY` varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`ID_CONSUME_SERVICE`) USING BTREE,
  INDEX `FK_RELATIONSHIP_108`(`ID_COST_SERVICE`) USING BTREE,
  INDEX `FK_RELATIONSHIP_111`(`ID_CHECK`) USING BTREE,
  INDEX `FK_RELATIONSHIP_84`(`ID_TYPE_CONSUME`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_108` FOREIGN KEY (`ID_COST_SERVICE`) REFERENCES `cost_service` (`ID_COST_SERVICE`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_111` FOREIGN KEY (`ID_CHECK`) REFERENCES `check_person` (`ID_CHECK`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_84` FOREIGN KEY (`ID_TYPE_CONSUME`) REFERENCES `type_consume` (`ID_TYPE_CONSUME`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 135 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for cost_food
-- ----------------------------
DROP TABLE IF EXISTS `cost_food`;
CREATE TABLE `cost_food`  (
  `ID_FOOD` int(11) NOT NULL,
  `ID_TYPE_MONEY` int(11) NOT NULL,
  `UNIT_COST_FOOD` decimal(3, 0) NOT NULL,
  `PRICE_COST_FOOD` float(8, 2) NOT NULL,
  `POINT_OBTAIN_COST_FOOD` decimal(6, 0) NOT NULL,
  `POINT_REQUIRED_COST_FOOD` decimal(6, 0) NOT NULL,
  `TIME_CREATED_COST_FOOD` time(0) NOT NULL,
  `DATE_CREATED_COST_FOOD` date NOT NULL,
  `ACTIVE_COST_FOOD` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_FOOD`, `ID_TYPE_MONEY`, `UNIT_COST_FOOD`) USING BTREE,
  INDEX `FK_RELATIONSHIP_96`(`ID_TYPE_MONEY`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_95` FOREIGN KEY (`ID_FOOD`) REFERENCES `food` (`ID_FOOD`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_96` FOREIGN KEY (`ID_TYPE_MONEY`) REFERENCES `type_money` (`ID_TYPE_MONEY`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for cost_service
-- ----------------------------
DROP TABLE IF EXISTS `cost_service`;
CREATE TABLE `cost_service`  (
  `ID_COST_SERVICE` int(11) NOT NULL AUTO_INCREMENT,
  `ID_SERVICE` int(11) NOT NULL,
  `ID_TYPE_MONEY` int(11) NOT NULL,
  `UNIT_COST_SERVICE` decimal(3, 0) NOT NULL,
  `UNIT_DAY_COST_SERVICE` decimal(2, 0) NOT NULL,
  `UNIT_HOUR_COST_SERVICE` decimal(2, 0) NOT NULL,
  `PRICE_COST_SERVICE` float(8, 2) NOT NULL,
  `POINT_OBTAIN_COST_SERVICE` decimal(6, 0) NOT NULL,
  `POINT_REQUIRED_COST_SERVICE` decimal(6, 0) NOT NULL,
  `ACTIVE_COST_SERVICE` tinyint(1) NOT NULL,
  `TIME_CREATED_COST_SERVICE` time(0) NOT NULL,
  `DATE_CREATED_COST_SERVICE` date NOT NULL,
  PRIMARY KEY (`ID_COST_SERVICE`) USING BTREE,
  INDEX `FK_RELATIONSHIP_112`(`ID_SERVICE`) USING BTREE,
  INDEX `FK_RELATIONSHIP_94`(`ID_TYPE_MONEY`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_112` FOREIGN KEY (`ID_SERVICE`) REFERENCES `service` (`ID_SERVICE`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_94` FOREIGN KEY (`ID_TYPE_MONEY`) REFERENCES `type_money` (`ID_TYPE_MONEY`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 24 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for food
-- ----------------------------
DROP TABLE IF EXISTS `food`;
CREATE TABLE `food`  (
  `ID_FOOD` int(11) NOT NULL AUTO_INCREMENT,
  `ID_TYPE_FOOD` int(11) NOT NULL,
  `ID_STATE_FOOD` int(11) NOT NULL,
  `NAME_FOOD` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_FOOD` varchar(350) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `IMAGE_FOOD` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`ID_FOOD`) USING BTREE,
  INDEX `FK_RELATIONSHIP_60`(`ID_TYPE_FOOD`) USING BTREE,
  INDEX `FK_RELATIONSHIP_83`(`ID_STATE_FOOD`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_60` FOREIGN KEY (`ID_TYPE_FOOD`) REFERENCES `type_food` (`ID_TYPE_FOOD`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_83` FOREIGN KEY (`ID_STATE_FOOD`) REFERENCES `state_food` (`ID_STATE_FOOD`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 111 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for form
-- ----------------------------
DROP TABLE IF EXISTS `form`;
CREATE TABLE `form`  (
  `ID_FORM` decimal(3, 0) NOT NULL,
  `NAME_FORM` char(25) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_FORM` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`ID_FORM`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for func_form
-- ----------------------------
DROP TABLE IF EXISTS `func_form`;
CREATE TABLE `func_form`  (
  `ID_FORM` decimal(3, 0) NOT NULL,
  `ID_FUNCTION` decimal(3, 0) NOT NULL,
  `DATE_FUNCTION_FORM` date NOT NULL,
  `TIME_FUNCTION_FORM` time(0) NOT NULL,
  PRIMARY KEY (`ID_FORM`, `ID_FUNCTION`) USING BTREE,
  INDEX `FK_RELATIONSHIP_10`(`ID_FUNCTION`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_10` FOREIGN KEY (`ID_FUNCTION`) REFERENCES `function` (`ID_FUNCTION`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_11` FOREIGN KEY (`ID_FORM`) REFERENCES `form` (`ID_FORM`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for function
-- ----------------------------
DROP TABLE IF EXISTS `function`;
CREATE TABLE `function`  (
  `ID_FUNCTION` decimal(3, 0) NOT NULL,
  `NAME_FUNCTION` char(25) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_FUNCTION` varchar(250) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `IMAGE_FUNCTION` varchar(250) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (`ID_FUNCTION`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for hotel
-- ----------------------------
DROP TABLE IF EXISTS `hotel`;
CREATE TABLE `hotel`  (
  `ID_HOTEL` int(11) NOT NULL AUTO_INCREMENT,
  `ID_TYPE_HOTEL` int(11) NOT NULL,
  `NAME_HOTEL` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DOMINIO_HOTEL` varchar(75) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_FOUNDATION_HOTEL` date NOT NULL,
  `LOGO_HOTEL` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `ADDRESS_HOTEL` varchar(250) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `ADDRESS_GPS_X_HOTEL` float NOT NULL,
  `ADDRESS_GPS_Y_HOTEL` float NOT NULL,
  `ADDRESS_IMAGE_HOTEL` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `HISTORY_HOTEL` varchar(5000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `MISSION_HOTEL` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VISION_HOTEL` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `SCOPE_HOTEL` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `OBJECTIVE_HOTEL` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `WATCHWORD_HOTEL` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_HOTEL` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `EMAIL_HOTEL` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `PHONE_HOTEL` decimal(15, 0) NOT NULL,
  PRIMARY KEY (`ID_HOTEL`) USING BTREE,
  INDEX `FK_RELATIONSHIP_46`(`ID_TYPE_HOTEL`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_46` FOREIGN KEY (`ID_TYPE_HOTEL`) REFERENCES `type_hotel` (`ID_TYPE_HOTEL`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for image_site_tour
-- ----------------------------
DROP TABLE IF EXISTS `image_site_tour`;
CREATE TABLE `image_site_tour`  (
  `ID_IMAGE_SITE` int(11) NOT NULL AUTO_INCREMENT,
  `ID_SITE_TOUR` int(11) NOT NULL,
  `IMAGE_SITE` varchar(250) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `NAME_IMAGE_SITE` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_IMAGE_SITE` varchar(750) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `STATE_IMAGE_SITE` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_IMAGE_SITE`) USING BTREE,
  INDEX `FK_RELATIONSHIP_44`(`ID_SITE_TOUR`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_44` FOREIGN KEY (`ID_SITE_TOUR`) REFERENCES `site_tour` (`ID_SITE_TOUR`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 42 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for inquest
-- ----------------------------
DROP TABLE IF EXISTS `inquest`;
CREATE TABLE `inquest`  (
  `ID_INQUEST` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PERSON` int(11) NOT NULL,
  `ID_STATE_INQUEST` int(11) NOT NULL,
  `NAME_INQUEST` varchar(250) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_INQUEST` varchar(750) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_START_INQUEST` date NOT NULL,
  `TIME_START_INQUEST` time(0) NOT NULL,
  `DATE_END_INQUEST` date DEFAULT NULL,
  `TIME_END_INQUEST` time(0) DEFAULT NULL,
  PRIMARY KEY (`ID_INQUEST`) USING BTREE,
  INDEX `FK_RELATIONSHIP_50`(`ID_PERSON`) USING BTREE,
  INDEX `FK_RELATIONSHIP_82`(`ID_STATE_INQUEST`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_50` FOREIGN KEY (`ID_PERSON`) REFERENCES `user_hotel` (`ID_PERSON`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_82` FOREIGN KEY (`ID_STATE_INQUEST`) REFERENCES `state_inquest` (`ID_STATE_INQUEST`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 7 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for log
-- ----------------------------
DROP TABLE IF EXISTS `log`;
CREATE TABLE `log`  (
  `ID_LOG` int(15) NOT NULL AUTO_INCREMENT,
  `ID_TYPE_LOG` int(11) NOT NULL,
  `ENTITY` char(25) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATA_NEW` varchar(350) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATA_OLD` varchar(350) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_CREATED_LOG` date NOT NULL,
  `TIME_CREATED_LOG` time(0) NOT NULL,
  `IP_LOG` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `BROWSER_LOG` varchar(300) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `SESSION_LOG` varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`ID_LOG`) USING BTREE,
  INDEX `FK_RELATIONSHIP_67`(`ID_TYPE_LOG`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_67` FOREIGN KEY (`ID_TYPE_LOG`) REFERENCES `type_log` (`ID_TYPE_LOG`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for member_check
-- ----------------------------
DROP TABLE IF EXISTS `member_check`;
CREATE TABLE `member_check`  (
  `ID_PERSON` int(11) NOT NULL,
  `ID_CONSUME_SERVICE` int(11) NOT NULL,
  `ACTIVE_MEMBER` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_PERSON`, `ID_CONSUME_SERVICE`) USING BTREE,
  INDEX `FK_RELATIONSHIP_115`(`ID_CONSUME_SERVICE`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_114` FOREIGN KEY (`ID_PERSON`) REFERENCES `person` (`ID_PERSON`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_115` FOREIGN KEY (`ID_CONSUME_SERVICE`) REFERENCES `consume_service` (`ID_CONSUME_SERVICE`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for menu
-- ----------------------------
DROP TABLE IF EXISTS `menu`;
CREATE TABLE `menu`  (
  `ID_MENU` int(11) NOT NULL AUTO_INCREMENT,
  `ACTIVE_MENU` tinyint(1) NOT NULL,
  `TIME_UPDATE_MENU` time(0) NOT NULL,
  `DATE_UPDATE_MENU` date NOT NULL,
  `TIME_CREATED_MENU` time(0) NOT NULL,
  `DATE_CREATED_MENU` date NOT NULL,
  `DATE_START_MENU` date NOT NULL,
  `DATE_END_MENU` date NOT NULL,
  `NAME_MENU` char(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`ID_MENU`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 9 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for menu_food
-- ----------------------------
DROP TABLE IF EXISTS `menu_food`;
CREATE TABLE `menu_food`  (
  `ID_FOOD` int(11) NOT NULL,
  `ID_MENU` int(11) NOT NULL,
  PRIMARY KEY (`ID_FOOD`, `ID_MENU`) USING BTREE,
  INDEX `FK_RELATIONSHIP_81`(`ID_MENU`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_117` FOREIGN KEY (`ID_FOOD`) REFERENCES `food` (`ID_FOOD`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_81` FOREIGN KEY (`ID_MENU`) REFERENCES `menu` (`ID_MENU`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for message
-- ----------------------------
DROP TABLE IF EXISTS `message`;
CREATE TABLE `message`  (
  `ID_MESSAGE` int(7) NOT NULL AUTO_INCREMENT,
  `SENDER_MESSAGE` int(11) NOT NULL,
  `RECEIVER_MESSAGE` int(11) NOT NULL,
  `ID_TYPE_MESSAGE` int(11) NOT NULL,
  `DATE_MESSAGE` date NOT NULL,
  `TIME_MESSAGE` time(0) NOT NULL,
  `STATE_MESSAGE` tinyint(1) NOT NULL,
  `TITTLE_MESSAGE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `CONTAINER_MESSAGE` varchar(750) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `IMAGE_MESSAGE` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (`ID_MESSAGE`) USING BTREE,
  INDEX `FK_RELATIONSHIP_55`(`SENDER_MESSAGE`) USING BTREE,
  INDEX `FK_RELATIONSHIP_79`(`RECEIVER_MESSAGE`) USING BTREE,
  INDEX `FK_RELATIONSHIP_99`(`ID_TYPE_MESSAGE`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_55` FOREIGN KEY (`SENDER_MESSAGE`) REFERENCES `user_hotel` (`ID_PERSON`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_79` FOREIGN KEY (`RECEIVER_MESSAGE`) REFERENCES `user_hotel` (`ID_PERSON`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_99` FOREIGN KEY (`ID_TYPE_MESSAGE`) REFERENCES `type_message` (`ID_TYPE_MESSAGE`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 1008 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for occupation
-- ----------------------------
DROP TABLE IF EXISTS `occupation`;
CREATE TABLE `occupation`  (
  `ID_CONSUME_SERVICE` int(11) NOT NULL,
  `ID_ROOM` int(11) NOT NULL,
  PRIMARY KEY (`ID_CONSUME_SERVICE`, `ID_ROOM`) USING BTREE,
  INDEX `FK_RELATIONSHIP_113`(`ID_ROOM`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_113` FOREIGN KEY (`ID_ROOM`) REFERENCES `room` (`ID_ROOM`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_116` FOREIGN KEY (`ID_CONSUME_SERVICE`) REFERENCES `consume_service` (`ID_CONSUME_SERVICE`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for offer
-- ----------------------------
DROP TABLE IF EXISTS `offer`;
CREATE TABLE `offer`  (
  `ID_OFFER` int(11) NOT NULL AUTO_INCREMENT,
  `ID_SERVICE` int(11) NOT NULL,
  `DATE_INI_OFFER` date NOT NULL,
  `TIME_INI_OFFER` time(0) NOT NULL,
  `DATE_FIN_OFFER` date NOT NULL,
  `TIME_FIN_OFFER` time(0) NOT NULL,
  `ACTIVE_OFFER` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_OFFER`) USING BTREE,
  INDEX `FK_RELATIONSHIP_74`(`ID_SERVICE`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_74` FOREIGN KEY (`ID_SERVICE`) REFERENCES `service` (`ID_SERVICE`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 5 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for person
-- ----------------------------
DROP TABLE IF EXISTS `person`;
CREATE TABLE `person`  (
  `ID_PERSON` int(7) NOT NULL AUTO_INCREMENT,
  `NAME_PERSON` char(25) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `LAST_NAME_PERSON` char(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `LAST_NAME_PERSON2` char(25) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `SEX_PERSON` tinyint(1) NOT NULL,
  `DATE_BORN_PERSON` date NOT NULL,
  `EMAIL_PERSON` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `CITY_PERSON` char(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `COUNTRY_PERSON` char(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `ADDRESS_PERSON` varchar(250) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_REGISTER_PERSON` date NOT NULL,
  `IMAGE_PROFILE` varchar(250) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `POINT_PERSON` int(11) NOT NULL,
  PRIMARY KEY (`ID_PERSON`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 141 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for person_document
-- ----------------------------
DROP TABLE IF EXISTS `person_document`;
CREATE TABLE `person_document`  (
  `NUMBER_DOCUMENT` decimal(25, 0) NOT NULL,
  `ID_TYPE_DOCUMENT` int(11) NOT NULL,
  `ID_PERSON` int(11) NOT NULL,
  `DATE_REGISTER_DOCUMENT` date NOT NULL,
  `TIME_REGISTER_DOCUMENT` time(0) NOT NULL,
  PRIMARY KEY (`NUMBER_DOCUMENT`) USING BTREE,
  INDEX `FK_RELATIONSHIP_3`(`ID_TYPE_DOCUMENT`) USING BTREE,
  INDEX `FK_TIENE`(`ID_PERSON`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_3` FOREIGN KEY (`ID_TYPE_DOCUMENT`) REFERENCES `type_document` (`ID_TYPE_DOCUMENT`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_TIENE` FOREIGN KEY (`ID_PERSON`) REFERENCES `person` (`ID_PERSON`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for person_phone
-- ----------------------------
DROP TABLE IF EXISTS `person_phone`;
CREATE TABLE `person_phone`  (
  `NUMBER_PHONE` decimal(10, 0) NOT NULL,
  `ID_PERSON` int(11) NOT NULL,
  `ID_TYPE_PHONE` int(11) NOT NULL,
  `DATE_REGISTER_PHONE` date NOT NULL,
  `TIME_REGISTER_PHONE` time(0) NOT NULL,
  PRIMARY KEY (`NUMBER_PHONE`) USING BTREE,
  INDEX `FK_RELATIONSHIP_126`(`ID_TYPE_PHONE`) USING BTREE,
  INDEX `FK_RELATIONSHIP_62`(`ID_PERSON`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_126` FOREIGN KEY (`ID_TYPE_PHONE`) REFERENCES `type_phone` (`ID_TYPE_PHONE`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_62` FOREIGN KEY (`ID_PERSON`) REFERENCES `person` (`ID_PERSON`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for question
-- ----------------------------
DROP TABLE IF EXISTS `question`;
CREATE TABLE `question`  (
  `ID_QUESTION` int(11) NOT NULL AUTO_INCREMENT,
  `ID_INQUEST` int(11) NOT NULL,
  `DESCRIPTION_QUESTION` varchar(250) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `ACTIVE_QUESTION` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_QUESTION`) USING BTREE,
  INDEX `FK_RELATIONSHIP_49`(`ID_INQUEST`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_49` FOREIGN KEY (`ID_INQUEST`) REFERENCES `inquest` (`ID_INQUEST`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 43 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for reserve
-- ----------------------------
DROP TABLE IF EXISTS `reserve`;
CREATE TABLE `reserve`  (
  `ID_CONSUME_SERVICE` int(11) NOT NULL,
  `ID_ROOM_MODEL` int(11) NOT NULL,
  `UNIT_RESERVED` int(11) NOT NULL,
  PRIMARY KEY (`ID_CONSUME_SERVICE`, `ID_ROOM_MODEL`) USING BTREE,
  INDEX `FK_RELATIONSHIP_118`(`ID_ROOM_MODEL`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_118` FOREIGN KEY (`ID_ROOM_MODEL`) REFERENCES `room_model` (`ID_ROOM_MODEL`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_119` FOREIGN KEY (`ID_CONSUME_SERVICE`) REFERENCES `consume_service` (`ID_CONSUME_SERVICE`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for response
-- ----------------------------
DROP TABLE IF EXISTS `response`;
CREATE TABLE `response`  (
  `ID_PERSON` int(11) NOT NULL,
  `ID_QUESTION` int(11) NOT NULL,
  `DESCRIPTION_RESPONSE` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_RESPONSE` date NOT NULL,
  `TIME_RESPONSE` time(0) NOT NULL,
  PRIMARY KEY (`ID_PERSON`, `ID_QUESTION`) USING BTREE,
  INDEX `FK_RELATIONSHIP_65`(`ID_QUESTION`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_64` FOREIGN KEY (`ID_PERSON`) REFERENCES `user_hotel` (`ID_PERSON`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_65` FOREIGN KEY (`ID_QUESTION`) REFERENCES `question` (`ID_QUESTION`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for rol
-- ----------------------------
DROP TABLE IF EXISTS `rol`;
CREATE TABLE `rol`  (
  `ID_ROL` int(2) NOT NULL AUTO_INCREMENT,
  `NAME_ROL` char(25) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_ROL` varchar(250) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `IMAGE_ROL` longblob,
  PRIMARY KEY (`ID_ROL`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 6 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for rol_function
-- ----------------------------
DROP TABLE IF EXISTS `rol_function`;
CREATE TABLE `rol_function`  (
  `ID_ROL` int(11) NOT NULL,
  `ID_FUNCTION` decimal(3, 0) NOT NULL,
  `DATE_CREATED_ROL_FUNCTION` date NOT NULL,
  `TIME_CREATED_ROL_FUNCTION` time(0) NOT NULL,
  PRIMARY KEY (`ID_ROL`, `ID_FUNCTION`) USING BTREE,
  INDEX `FK_RELATIONSHIP_9`(`ID_FUNCTION`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_8` FOREIGN KEY (`ID_ROL`) REFERENCES `rol` (`ID_ROL`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_9` FOREIGN KEY (`ID_FUNCTION`) REFERENCES `function` (`ID_FUNCTION`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for rol_inquest
-- ----------------------------
DROP TABLE IF EXISTS `rol_inquest`;
CREATE TABLE `rol_inquest`  (
  `ID_ROL` int(11) NOT NULL,
  `ID_INQUEST` int(11) NOT NULL,
  PRIMARY KEY (`ID_ROL`, `ID_INQUEST`) USING BTREE,
  INDEX `FK_RELATIONSHIP_53`(`ID_INQUEST`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_52` FOREIGN KEY (`ID_ROL`) REFERENCES `rol` (`ID_ROL`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_53` FOREIGN KEY (`ID_INQUEST`) REFERENCES `inquest` (`ID_INQUEST`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for room
-- ----------------------------
DROP TABLE IF EXISTS `room`;
CREATE TABLE `room`  (
  `ID_ROOM` int(11) NOT NULL AUTO_INCREMENT,
  `NAME_ROOM` varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `ID_HOTEL` int(11) NOT NULL,
  `ID_ROOM_MODEL` int(11) NOT NULL,
  `IMAGE_ROOM` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `STATE_ROOM` decimal(1, 0) NOT NULL,
  `DATE_CREATED_ROOM` date NOT NULL,
  `TIME_CREATED_ROOM` time(0) NOT NULL,
  `DATE_CHECK_OUT_ROOM` date NOT NULL,
  `TIME_CHECK_OUT_ROOM` time(0) NOT NULL,
  `DATE_CHECK_IN_ROOM` date NOT NULL,
  `TIME_CHECK_IN_ROOM` time(0) NOT NULL,
  PRIMARY KEY (`ID_ROOM`) USING BTREE,
  INDEX `FK_RELATIONSHIP_107`(`ID_HOTEL`) USING BTREE,
  INDEX `FK_RELATIONSHIP_43`(`ID_ROOM_MODEL`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_107` FOREIGN KEY (`ID_HOTEL`) REFERENCES `hotel` (`ID_HOTEL`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_43` FOREIGN KEY (`ID_ROOM_MODEL`) REFERENCES `room_model` (`ID_ROOM_MODEL`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 93 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for room_model
-- ----------------------------
DROP TABLE IF EXISTS `room_model`;
CREATE TABLE `room_model`  (
  `ID_ROOM_MODEL` int(2) NOT NULL AUTO_INCREMENT,
  `NAME_ROOM_MODEL` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_ROOM_MODEL` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_CREATED_ROOM_MODEL` date NOT NULL,
  `TIME_CREATED_ROOM_MODEL` time(0) NOT NULL,
  `IMAGE_ROOM_MODEL` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `UNIT_ADULT_ROOM_MODEL` decimal(2, 0) NOT NULL,
  `UNIT_BOY_ROOM_MODEL` decimal(2, 0) NOT NULL,
  `UNIT_PET_ROOM_MODEL` decimal(2, 0) NOT NULL,
  `VALUE_TYPE_ROOM_MODEL` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_ROOM_MODEL`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 11 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for rule
-- ----------------------------
DROP TABLE IF EXISTS `rule`;
CREATE TABLE `rule`  (
  `ID_TYPE_RULE` int(11) NOT NULL,
  `ID_HOTEL` int(11) NOT NULL,
  `NAME_RULE` varchar(250) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_RULE` varchar(750) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `STATE_RULE` decimal(1, 0) NOT NULL,
  PRIMARY KEY (`ID_TYPE_RULE`, `ID_HOTEL`, `NAME_RULE`) USING BTREE,
  INDEX `FK_RELATIONSHIP_47`(`ID_HOTEL`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_47` FOREIGN KEY (`ID_HOTEL`) REFERENCES `hotel` (`ID_HOTEL`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_48` FOREIGN KEY (`ID_TYPE_RULE`) REFERENCES `type_rule` (`ID_TYPE_RULE`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for service
-- ----------------------------
DROP TABLE IF EXISTS `service`;
CREATE TABLE `service`  (
  `ID_SERVICE` int(2) NOT NULL AUTO_INCREMENT,
  `ID_STATE_SERVICE` int(11) NOT NULL,
  `ID_HOTEL` int(11) NOT NULL,
  `ID_TYPE_SERVICE` int(11) NOT NULL,
  `NAME_SERVICE` char(75) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_SERVICE` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `IMAGE_SERVICE` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `RESERVED_SERVICE` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_SERVICE`) USING BTREE,
  INDEX `FK_RELATIONSHIP_23`(`ID_TYPE_SERVICE`) USING BTREE,
  INDEX `FK_RELATIONSHIP_66`(`ID_HOTEL`) USING BTREE,
  INDEX `FK_RELATIONSHIP_97`(`ID_STATE_SERVICE`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_23` FOREIGN KEY (`ID_TYPE_SERVICE`) REFERENCES `type_service` (`ID_TYPE_SERVICE`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_66` FOREIGN KEY (`ID_HOTEL`) REFERENCES `hotel` (`ID_HOTEL`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_97` FOREIGN KEY (`ID_STATE_SERVICE`) REFERENCES `state_service` (`ID_STATE_SERVICE`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 18 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for service_activity
-- ----------------------------
DROP TABLE IF EXISTS `service_activity`;
CREATE TABLE `service_activity`  (
  `ID_SERVICE` int(11) NOT NULL,
  `ID_ACTIVITY` int(11) NOT NULL,
  `DATE_INI_ACTIVITY` datetime(0) NOT NULL,
  `DATE_FIN_ACTIVITY` datetime(0) NOT NULL,
  PRIMARY KEY (`ID_SERVICE`, `ID_ACTIVITY`) USING BTREE,
  INDEX `FK_RELATIONSHIP_40`(`ID_ACTIVITY`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_40` FOREIGN KEY (`ID_ACTIVITY`) REFERENCES `activity` (`ID_ACTIVITY`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_41` FOREIGN KEY (`ID_SERVICE`) REFERENCES `service` (`ID_SERVICE`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for service_function
-- ----------------------------
DROP TABLE IF EXISTS `service_function`;
CREATE TABLE `service_function`  (
  `ID_SERVICE` int(11) NOT NULL,
  `ID_FUNCTION` decimal(3, 0) NOT NULL,
  PRIMARY KEY (`ID_SERVICE`, `ID_FUNCTION`) USING BTREE,
  INDEX `FK_RELATIONSHIP_75`(`ID_FUNCTION`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_75` FOREIGN KEY (`ID_FUNCTION`) REFERENCES `function` (`ID_FUNCTION`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_76` FOREIGN KEY (`ID_SERVICE`) REFERENCES `service` (`ID_SERVICE`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for service_incharge
-- ----------------------------
DROP TABLE IF EXISTS `service_incharge`;
CREATE TABLE `service_incharge`  (
  `ID_PERSON` int(11) NOT NULL,
  `ID_SERVICE` int(11) NOT NULL,
  PRIMARY KEY (`ID_PERSON`, `ID_SERVICE`) USING BTREE,
  INDEX `FK_RELATIONSHIP_103`(`ID_SERVICE`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_103` FOREIGN KEY (`ID_SERVICE`) REFERENCES `service` (`ID_SERVICE`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_104` FOREIGN KEY (`ID_PERSON`) REFERENCES `person` (`ID_PERSON`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for service_room_model
-- ----------------------------
DROP TABLE IF EXISTS `service_room_model`;
CREATE TABLE `service_room_model`  (
  `ID_ROOM_MODEL` int(11) NOT NULL,
  `ID_SERVICE` int(11) NOT NULL,
  `UNIT_ROOM_MODEL` decimal(3, 0) NOT NULL,
  `DATE_CREATED_SERVICE_ROOM_MODEL` date NOT NULL,
  `TIME_CREAED_SERVICE_ROOM_MODEL` time(0) NOT NULL,
  PRIMARY KEY (`ID_ROOM_MODEL`, `ID_SERVICE`) USING BTREE,
  INDEX `FK_RELATIONSHIP_78`(`ID_SERVICE`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_78` FOREIGN KEY (`ID_SERVICE`) REFERENCES `service` (`ID_SERVICE`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_91` FOREIGN KEY (`ID_ROOM_MODEL`) REFERENCES `room_model` (`ID_ROOM_MODEL`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for session
-- ----------------------------
DROP TABLE IF EXISTS `session`;
CREATE TABLE `session`  (
  `ID_SESSION` int(15) NOT NULL AUTO_INCREMENT,
  `ID_PERSON` int(11) DEFAULT NULL,
  `IP_PROXI` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `IP_MULTIUSER` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `IP_CLIENT` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `PID` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_START` date NOT NULL,
  `DATE_END` date NOT NULL,
  `BROWSER` varchar(300) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `TIME_START` time(0) NOT NULL,
  `TIME_END` time(0) NOT NULL,
  `ACTIVED` tinyint(1) NOT NULL,
  `LATITUD` varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `LONGITUD` varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `CITY` varchar(25) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `REGION` varchar(25) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `AREA_CODE` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `COUNTRY` varchar(25) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `REGION_CODE` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`ID_SESSION`) USING BTREE,
  INDEX `FK_RELATIONSHIP_20`(`ID_PERSON`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_20` FOREIGN KEY (`ID_PERSON`) REFERENCES `user_hotel` (`ID_PERSON`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 89 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for site_tour
-- ----------------------------
DROP TABLE IF EXISTS `site_tour`;
CREATE TABLE `site_tour`  (
  `ID_SITE_TOUR` int(11) NOT NULL AUTO_INCREMENT,
  `ADDRESS_GPS_X_SITE_TOUR` float NOT NULL,
  `ADDRESS_GPS_Y_SITE_TOUR` float NOT NULL,
  `ID_HOTEL` int(11) NOT NULL,
  `NAME_SITE_TOUR` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_SITE_TOUR` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `ADDRESS_SITE_TOUR` varchar(250) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `STATE_SITE_TOUR` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_SITE_TOUR`) USING BTREE,
  INDEX `FK_RELATIONSHIP_101`(`ID_HOTEL`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_101` FOREIGN KEY (`ID_HOTEL`) REFERENCES `hotel` (`ID_HOTEL`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 11 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for state_activity
-- ----------------------------
DROP TABLE IF EXISTS `state_activity`;
CREATE TABLE `state_activity`  (
  `ID_STATE_ACTIVITY` int(2) NOT NULL AUTO_INCREMENT,
  `NAME_STATE_ACTIVITY` char(25) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_STATE_ACTIVITY` varchar(150) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VALUE_STATE_ACTIVITY` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_STATE_ACTIVITY`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 4 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for state_article
-- ----------------------------
DROP TABLE IF EXISTS `state_article`;
CREATE TABLE `state_article`  (
  `ID_STATE_ARTICLE` int(11) NOT NULL AUTO_INCREMENT,
  `NAME_STATE_ARTICLE` char(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_STATE_ARTICLE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VALUE_STATE_ARTICLE` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_STATE_ARTICLE`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 5 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for state_check
-- ----------------------------
DROP TABLE IF EXISTS `state_check`;
CREATE TABLE `state_check`  (
  `ID_STATE_CHECK` int(11) NOT NULL AUTO_INCREMENT,
  `NAME_STATE_CHECK` char(25) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_STATE_CHECK` char(75) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VALUE_STATE_CHECK` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_STATE_CHECK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 9 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for state_food
-- ----------------------------
DROP TABLE IF EXISTS `state_food`;
CREATE TABLE `state_food`  (
  `ID_STATE_FOOD` int(2) NOT NULL AUTO_INCREMENT,
  `NAME_STATE_FOOD` char(25) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_STATE_FOOD` varchar(150) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VALUE_STATE_FOOD` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_STATE_FOOD`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 4 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for state_inquest
-- ----------------------------
DROP TABLE IF EXISTS `state_inquest`;
CREATE TABLE `state_inquest`  (
  `ID_STATE_INQUEST` int(2) NOT NULL AUTO_INCREMENT,
  `NAME_STATE_INQUEST` char(25) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_STATE_INQUEST` varchar(150) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VALUE_STATE_INQUEST` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_STATE_INQUEST`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 7 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for state_service
-- ----------------------------
DROP TABLE IF EXISTS `state_service`;
CREATE TABLE `state_service`  (
  `ID_STATE_SERVICE` int(2) NOT NULL AUTO_INCREMENT,
  `NAME_STATE_SERVICE` char(25) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_STATE_SERVICE` varchar(150) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VALUE_STATE_SERVICE` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_STATE_SERVICE`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 5 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for state_user
-- ----------------------------
DROP TABLE IF EXISTS `state_user`;
CREATE TABLE `state_user`  (
  `ID_STATE_USER` int(2) NOT NULL AUTO_INCREMENT,
  `NAME_STATE_USER` char(25) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_STATE_USER` varchar(150) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VALUE_STATE_USER` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_STATE_USER`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 5 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for type_activity
-- ----------------------------
DROP TABLE IF EXISTS `type_activity`;
CREATE TABLE `type_activity`  (
  `ID_TYPE_ACTIVITY` int(2) NOT NULL AUTO_INCREMENT,
  `NAME_TYPE_ACTIVITY` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_TYPE_ACTIVITY` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_TYPE_ACTIVITY` date NOT NULL,
  `TIME_TYPE_ACTIVITY` time(0) NOT NULL,
  `IMAGE_TYPE_ACTIVITY` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VALUE_TYPE_ACTIVITY` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_TYPE_ACTIVITY`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 6 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for type_card
-- ----------------------------
DROP TABLE IF EXISTS `type_card`;
CREATE TABLE `type_card`  (
  `ID_TYPE_CARD` int(2) NOT NULL AUTO_INCREMENT,
  `NAME_TYPE_CARD` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_TYPE_CARD` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_TYPE_CARD` date NOT NULL,
  `TIME_TYPE_CARD` time(0) NOT NULL,
  `IMAGE_TYPE_CARD` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VALUE_TYPE_CARD` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_TYPE_CARD`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 5 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for type_check
-- ----------------------------
DROP TABLE IF EXISTS `type_check`;
CREATE TABLE `type_check`  (
  `ID_TYPE_CHECK` int(2) NOT NULL AUTO_INCREMENT,
  `NAME_TYPE_CHECK` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_TYPE_CHECK` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_TYPE_CHECK` date NOT NULL,
  `TIME_TYPE_CHECK` time(0) NOT NULL,
  `IMAGE_TYPE_CHECK` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VALUE_TYPE_CHECK` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_TYPE_CHECK`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 4 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for type_consume
-- ----------------------------
DROP TABLE IF EXISTS `type_consume`;
CREATE TABLE `type_consume`  (
  `ID_TYPE_CONSUME` int(2) NOT NULL AUTO_INCREMENT,
  `NAME_TYPE_CONSUME` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_TYPE_CONSUME` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_TYPE_CONSUME` date NOT NULL,
  `TIME_TYPE_CONSUME` time(0) NOT NULL,
  `IMAGE_TYPE_CONSUME` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VALUE_TYPE_CONSUME` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_TYPE_CONSUME`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 9 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for type_document
-- ----------------------------
DROP TABLE IF EXISTS `type_document`;
CREATE TABLE `type_document`  (
  `ID_TYPE_DOCUMENT` int(2) NOT NULL AUTO_INCREMENT,
  `NAME_TYPE_DOCUMENT` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_TYPE_DOCUMENT` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_TYPE_DOCUMENT` date NOT NULL,
  `TIME_TYPE_DOCUMENT` time(0) NOT NULL,
  `IMAGE_TYPE_DOCUMENT` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VALUE_TYPE_DOCUMENT` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_TYPE_DOCUMENT`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 5 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for type_food
-- ----------------------------
DROP TABLE IF EXISTS `type_food`;
CREATE TABLE `type_food`  (
  `ID_TYPE_FOOD` int(2) NOT NULL AUTO_INCREMENT,
  `NAME_TYPE_FOOD` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_TYPE_FOOD` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_TYPE_FOOD` date NOT NULL,
  `TIME_TYPE_FOOD` time(0) NOT NULL,
  `IMAGE_TYPE_FOOD` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VALUE_TYPE_FOOD` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_TYPE_FOOD`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 12 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for type_hotel
-- ----------------------------
DROP TABLE IF EXISTS `type_hotel`;
CREATE TABLE `type_hotel`  (
  `ID_TYPE_HOTEL` int(2) NOT NULL AUTO_INCREMENT,
  `NAME_TYPE_HOTEL` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_TYPE_HOTEL` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_TYPE_HOTEL` date NOT NULL,
  `TIME_TYPE_HOTEL` time(0) NOT NULL,
  `IMAGE_TYPE_HOTEL` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VALUE_TYPE_HOTEL` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_TYPE_HOTEL`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 11 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for type_log
-- ----------------------------
DROP TABLE IF EXISTS `type_log`;
CREATE TABLE `type_log`  (
  `ID_TYPE_LOG` int(2) NOT NULL AUTO_INCREMENT,
  `NAME_TYPE_LOG` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCR_TYPE_LOG` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_TYPE_LOG` date NOT NULL,
  `TIME_TYPE_LOG` time(0) NOT NULL,
  `IMAGE_TYPE_LOG` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VALUE_TYPE_LOG` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_TYPE_LOG`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 5 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for type_message
-- ----------------------------
DROP TABLE IF EXISTS `type_message`;
CREATE TABLE `type_message`  (
  `ID_TYPE_MESSAGE` int(2) NOT NULL AUTO_INCREMENT,
  `NAME_TYPE_MESSAGE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_TYPE_MESSAGE` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_TYPE_MESSAGE` date NOT NULL,
  `TIME_TYPE_MESSAGE` time(0) NOT NULL,
  `IMAGE_TYPE_MESSAGE` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VALUE_TYPE_MESSAGE` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_TYPE_MESSAGE`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 17 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for type_money
-- ----------------------------
DROP TABLE IF EXISTS `type_money`;
CREATE TABLE `type_money`  (
  `ID_TYPE_MONEY` int(2) NOT NULL AUTO_INCREMENT,
  `NAME_TYPE_MONEY` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_TYPE_MONEY` varchar(75) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_TYPE_MONEY` date NOT NULL,
  `TIME_TYPE_MONEY` time(0) NOT NULL,
  `IMAGE_TYPE_MONEY` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VALUE_TYPE_MONEY` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_TYPE_MONEY`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for type_phone
-- ----------------------------
DROP TABLE IF EXISTS `type_phone`;
CREATE TABLE `type_phone`  (
  `ID_TYPE_PHONE` int(2) NOT NULL AUTO_INCREMENT,
  `NAME_TYPE_PHONE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_TYPE_PHONE` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_TYPE_PHONE` date NOT NULL,
  `TIME_TYPE_PHONE` time(0) NOT NULL,
  `IMAGE_TYPE_PHONE` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VALUE_TYPE_PHONE` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_TYPE_PHONE`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 5 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for type_rule
-- ----------------------------
DROP TABLE IF EXISTS `type_rule`;
CREATE TABLE `type_rule`  (
  `ID_TYPE_RULE` int(2) NOT NULL AUTO_INCREMENT,
  `NAME_TYPE_RULE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_TYPE_RULE` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_TYPE_RULE` date NOT NULL,
  `TIME_TYPE_RULE` time(0) NOT NULL,
  `IMAGE_TYPE_RULE` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VALUE_TYPE_RULE` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_TYPE_RULE`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 5 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for type_service
-- ----------------------------
DROP TABLE IF EXISTS `type_service`;
CREATE TABLE `type_service`  (
  `ID_TYPE_SERVICE` int(2) NOT NULL AUTO_INCREMENT,
  `NAME_TYPE_SERVICE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DESCRIPTION_TYPE_SERVICE` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE_TYPE_SERVICE` date NOT NULL,
  `TIME_TYPE_SERVICE` time(0) NOT NULL,
  `IMAGE_TYPE_SERVICE` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VALUE_TYPE_SERVICE` decimal(2, 0) NOT NULL,
  PRIMARY KEY (`ID_TYPE_SERVICE`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 5 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for user_hotel
-- ----------------------------
DROP TABLE IF EXISTS `user_hotel`;
CREATE TABLE `user_hotel`  (
  `ID_PERSON` int(11) NOT NULL,
  `PASSWORD` varchar(250) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `ID_STATE_USER` int(11) NOT NULL,
  PRIMARY KEY (`ID_PERSON`) USING BTREE,
  INDEX `FK_RELATIONSHIP_71`(`ID_STATE_USER`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_31` FOREIGN KEY (`ID_PERSON`) REFERENCES `person` (`ID_PERSON`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_71` FOREIGN KEY (`ID_STATE_USER`) REFERENCES `state_user` (`ID_STATE_USER`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for user_name
-- ----------------------------
DROP TABLE IF EXISTS `user_name`;
CREATE TABLE `user_name`  (
  `ID_PERSON` int(11) NOT NULL,
  `NAME_USER` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `ACTIVE_USER` tinyint(1) NOT NULL,
  `DATE_REGISTER_NAME_USER` date NOT NULL,
  `TIME_REGISTER_NAME_USER` time(0) NOT NULL,
  PRIMARY KEY (`NAME_USER`) USING BTREE,
  INDEX `FK_RELATIONSHIP_80`(`ID_PERSON`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_80` FOREIGN KEY (`ID_PERSON`) REFERENCES `user_hotel` (`ID_PERSON`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for user_rol
-- ----------------------------
DROP TABLE IF EXISTS `user_rol`;
CREATE TABLE `user_rol`  (
  `ID_PERSON` int(11) NOT NULL,
  `ID_ROL` int(11) NOT NULL,
  `DATE_CREATED_ROL` date NOT NULL,
  `TIME_CREATED_ROL` time(0) NOT NULL,
  PRIMARY KEY (`ID_PERSON`, `ID_ROL`) USING BTREE,
  INDEX `FK_RELATIONSHIP_6`(`ID_ROL`) USING BTREE,
  CONSTRAINT `FK_RELATIONSHIP_5` FOREIGN KEY (`ID_PERSON`) REFERENCES `user_hotel` (`ID_PERSON`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_RELATIONSHIP_6` FOREIGN KEY (`ID_ROL`) REFERENCES `rol` (`ID_ROL`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

SET FOREIGN_KEY_CHECKS = 1;
